site_name: BentoBox World
copyright: "© Copyright 2017-2023 Tastybento, Poslovitch and the BentoBoxWorld community (CC-BY 4.0)."
repo_url: https://github.com/BentoBoxWorld/BentoBox
repo_name: BentoBoxWorld/BentoBox
edit_uri: ""
nav:
    - Home: index.md
    - "What does BentoBox do?":
        - Team Handling: BentoBox/About/Teams.md
        - Protection: BentoBox/About/Protections.md
    - FAQ: FAQ.md
    - Game Modes:
        - BSkyBlock: gamemodes/BSkyBlock/index.md
        - Boxed: gamemodes/Boxed/index.md
        - AcidIsland: gamemodes/AcidIsland/index.md
        - SkyGrid: gamemodes/SkyGrid/index.md
        - CaveBlock: gamemodes/CaveBlock/index.md
        - AOneBlock: gamemodes/AOneBlock/index.md
    - Addons:
        - Bank: addons/Bank/index.md
        - Biomes: addons/Biomes/index.md
        - Border: addons/Border/index.md
        - CauldronWitchery: addons/CauldronWitchery/index.md
        - Challenges: addons/Challenges/index.md
        - Chat: addons/Chat/index.md
        - CheckMeOut: addons/CheckMeOut/index.md
        - ControlPanel: addons/ControlPanel/index.md
        - DimensionalTrees: addons/DimensionalTrees/index.md
        - ExtraMobs: addons/ExtraMobs/index.md
        - FarmersDance: addons/FarmersDance/index.md
        - Greenhouses: addons/Greenhouses/index.md
        - InvSwitcher: addons/InvSwitcher/index.md
        - IslandFly: addons/IslandFly/index.md
        - Level: addons/Level/index.md
        - Likes: addons/Likes/index.md
        - Limits: addons/Limits/index.md
        - MagicCobblestoneGenerator: addons/MagicCobblestoneGenerator/index.md
        - TwerkingForTrees: addons/TwerkingForTrees/index.md
        - Visit: addons/Visit/index.md
        - VoidPortals: addons/VoidPortals/index.md
        - Warps: addons/Warps/index.md
        - Upgrades: addons/Upgrades/index.md
    - "Tutorials – Generic":
        - "How To Install": BentoBox/Install-Bentobox.md
        - "Set a BentoBox world as the server's default world": BentoBox/Set-a-BentoBox-world-as-the-server-default-world.md
        - "Database transition": BentoBox/Database-transition.md
    - "Tutorials – API":
        - "Create an Addon": Tutorials/api/Create-an-addon.md
        - "Config API": BentoBox/Config-API.md
        - "Database API": BentoBox/Database-API.md
        - "Metadata API": BentoBox/MetadataAPI.md
        - "Get Data From Addons": BentoBox/Request-Handler-API---How-plugins-can-get-data-from-addons.md
theme:
  name: material
  font: false
  palette:
    scheme: slate
    primary: deep orange
    accent: green
  icon:
    repo: fontawesome/brands/git-alt
extra_css:
  - stylesheets/icons-minecraft-0.5.css
  - stylesheets/harmonyos_sans.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BentoBoxWorld
      name: BentoBoxWorld 的 GitHub
    - icon: fontawesome/brands/jenkins
      link: https://ci.bentobox.world
      name: BentoBoxWorld 的 CodeMC CI
    - icon: fontawesome/brands/discord
      link: https://discord.bentobox.world
      name: BentoBoxWorld 的 Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCPaNnfxhr1-wCy0KBs9PLdQ
      name: YouTube 上的 BentoBoxWorld
    - icon: fontawesome/brands/bilibili
      link: https://www.bilibili.com/video/BV1Qc411h7Ug?spm_id_from=333.999.section.playall
      name: 哔哩哔哩教程视频
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/tastybento
      name: Sponsor tastybento on GitHub Sponsors
    - icon: fontawesome/solid/pen
      link: https://github.com/NetheriteTree/BentoboxDocs
      name: 协助完善此翻译
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.escapeall
  - pymdownx.progressbar
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: "#"
plugins:
  - search
  - minify:
      minify_html: true
  - macros
  - i18n:
      default_language: zh
      languages:
        en:
          name: English
          site_name: BentoBox World
        zh:
          name: 简体中文
          site_name: BentoBox 帮助文档
      nav_translations:
        zh:
          "Home": "首页"
          "What does BentoBox do?": "BentoBox 功能"
          "Team Handling": "团队系统"
          "Protection": "保护系统"
          "FAQ": "常见问题"
          "Game Modes": "游戏模式"
          "Addons": "扩展"
          "Tutorials – Generic": "插件基础"
          "How To Install": "安装教程"
          "Set a BentoBox world as the server's default world": "将 BentoBox 世界设为服务器默认世界"
          "Database transition": "迁移数据"
          "Tutorials – API": "API 文档"
          "Create an Addon": "制作扩展"
          "Config API": "Config API"
          "Database API": "Database API"
          "Metadata API": "Metadata API"
          "Get Data From Addons": "获取扩展数据"
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
